### ISSUE TITLE
Filenames not masked or hashed in Dropbox, causing name collisions

### ISSUE THREAD

**Issue by allanbreyes** [standardnotes/filesafe-relay#1]
OS: Ubuntu 18.04 LTS
SN Version: 3.01

I'm unsure if this is intended design, but I poked around the FileSafe directory, and was surprised to see the filenames of uploads. Although the content is encrypted, the filename is not obfuscated. However, more importantly, it appears to key off of the filename, which leads to collisions.

Repro:
1. In some note A, attach file `foo.txt` with content `bar`.
2. In some note B, attach file `foo.txt` with content `baz`.
3. Observe: both notes now have content `baz`.
4. Delete `foo.txt` in either.
5. Observe: both notes attachments are deleted.

Been a while since I dug into a Rails app, but happy to dig into it further and open a PR if you have any tips or pointers.

**Comment by mobitar** [comment]
Hey @allanbreyes, indeed, filenames are not currently encrypted. The idea was to make these files easier to identify without using SN, thus preserving the longevity aspect of not being tied down to SN or FileSafe. But, a lot of users have mentioned that they would like the option to encrypt file names. So this will likely be an option in a future update.

**Comment by allanbreyes** [comment]
Thanks for the response! Any comments regarding the name collision? Or is that expected? It seems like this can be resolved if it's hashed by `note_id, filename` or, alternatively, by content.

**Comment by mobitar** [comment]
Yeah, we'll need to add a unique identifier to each file to avoid name collisions. Could be easily done, since each file will have a unique UUID. I'll be making both these changes for the next update.

**Comment by allanbreyes** [comment]
Great! Looking forward to it. Thanks.

**Comment by mobitar** [comment]
File names will now be encrypted by default in FileSafe v2 (for new uploads only; existing files will be unaffected).
