### ISSUE TITLE
Support Backblaze b2

### ISSUE THREAD

**Issue by lukf** [standardnotes/filesafe-relay#10]
Backblaze B2 is very similar to Amazon S3, but
• Operated by a less terrible company
• Cheaper

I use B2 for many things and would also like to use it with FileSafe.

**Comment by stevesbrain** [comment]
This should be more possible now, given they have an S3 API too!

**Comment by JaspalSuri** [comment]
Thanks for the suggestion; I'll be sure to take note of this!

**Comment by vgroenewold** [comment]
Yes please, that would be awesome!
