### ISSUE TITLE
Offer copying link when adding new integration; clarify language

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/filesafe-relay#16]
When under Integrations you click the "Add new" button, the text says "A new tab has opened."

Depending on your path environment, OS settings, browser settings, etc., a new tab may not open, as is with my current setup. Thus the adding can't be completed. Could you please make the link copiable somehow? E.g. by appending a clickable text that copies the link to the clipboard.

Also, I suggest clearer phrasing of what happens, or is supposed to happen, so it's clearer to mitigate when it doesn't. E,g, modifying the first sentence, so it would ultimately look like this:

> A new tab in your browser will soon open. (If it doesn't, [click here](https://standardnotes.org) to copy the link, then paste it into your browser manually.)

**Comment by mobitar** [comment]
Hmm, good point, thanks.
