### ISSUE TITLE
Keep getting an error message when trying to upload

### ISSUE THREAD

**Issue by BobWs** [standardnotes/filesafe-relay#29]
Hi,
I'm self-hosted the standardnotes/syncing-server and standardnotes/web on docker on a Synology NAS.
And now I'm trying to self-host the standardnotes-filesafe-relay but I keep getting an error when uploading files/pictures.
I've installed everything according to your descriptions and I can configure the webdav server but then when uploading I get the error and nothing is being uploaded.

![Screen_Shot](https://user-images.githubusercontent.com/5485820/91633008-3be70580-e9e5-11ea-932b-df772e189193.png)

![Screen_Shot 1](https://user-images.githubusercontent.com/5485820/91633011-40132300-e9e5-11ea-938e-3549ddd92c93.png)

This is what I see when the filesafe-relay container is running and I put in here my login credentials.
It then generates a key and thats the key I put in the FileSafe extension. 

Standardnotes server and web are running fine and FileSafe extension is working with the default integration (filesafe.standardnotes.org) but I would like to host my own relay-server.

Can anyone point my in the direction to solve this?

**Comment by mobitar** [comment]
You'd need to check logs on your own server to see what the reported error is. There's not enough information in this issue to deduce what is happening.
