### ISSUE TITLE
Selfhost FileSafe keeps relaying me to the default FileSafe site of standardnotes

### ISSUE THREAD

**Issue by BobWs** [standardnotes/filesafe-relay#30]
I'm self-hosting the standardnotes/syncing-server, standardnotes/web and **standardnotes/filesafe**, on docker on a Synology NAS.

So far everything works fine except for some minor problems. 

At filesafe I have entered my own Subdomain in the configuration but if I want to enter my own davserver through the bold extension I’m being redirected to the standard filesafe link `filesafe.standardnotes.org.` I have to manually change the link in the browser to my own Sub-domain. (For example `filesafe.mydomain.com`).
 
Is there a possibility to change this somewhere in the configuration?

If my users do not pay attention when setting up their standardnotes account then all filesafe uploads are routed through the standard standardnotes filesafe link and not through my own filesafe relay.

**Comment by mobitar** [comment]
You would have to compile your own Bold Editor I believe as the relay URL is hard coded. https://github.com/standardnotes/filesafe-embed/blob/master/app/index.html#L7

**Comment by BobWs** [comment]
> You would have to compile your own Bold Editor I believe as the relay URL is hard coded. https://github.com/standardnotes/filesafe-embed/blob/master/app/index.html#L7

Okay, but wouldn’t it be better to make it a choice and added it as a configuration option e.g. through Docker environment.

**Comment by mobitar** [comment]
Yup definitely. If I were writing this today it would be much different. But for now this is a todo for us.
